#!/usr/bin/env bash

set -e

KSPPCNT=`systemctl --system show-environment | grep '^KSPPCNT=' | awk -F= '{print $2}'`
if [ "$KSPPCNT" = '' ]; then
  KSPPCNT=0
fi
KSPPCNT=$(( KSPPCNT + 1))

KSPP=`systemctl --system show-environment | grep '^KSPP=' | awk -F= '{print $2}'`
if [ "$KSPP" != '' ]; then
  echo -n $KSPP;
  systemctl --system set-environment KSPPCNT=$KSPPCNT
  exit 0;
fi

. /etc/sysconfig/mandos-keyscript

if [ "$MANDOS_CLIENT_INTERFACE" = 'auto' ]; then
  MANDOS_CLIENT_INTERFACE=`ip -4 route ls | grep default | awk '{print $5}'`
fi
if [ "$MANDOS_CLIENT_INTERFACE" != '' ]; then
  MANDOS_CLIENT_PARAMS="--interface=$MANDOS_CLIENT_INTERFACE $MANDOS_CLIENT_PARAMS"
fi

PARAMS="\
--delay=60 \
--retry=10 \
--pubkey=/etc/keys/mandos/pubkey.txt \
--seckey=/etc/keys/mandos/seckey.txt \
$MANDOS_CLIENT_PARAMS \
"
if [ "$MANDOS_SERVER" != '' ]; then
  IP=`getent ahosts $MANDOS_SERVER | head -1 | awk '{print $1}'`
  if [ "$IP" = '' ]; then
    echo "No Mandos Server IP/Domain specified!";
    exit 1;
  fi
  PARAMS="$PARAMS --connect=$IP:$MANDOS_PORT"
fi

KSPP=`/usr/lib/x86_64-linux-gnu/mandos/plugins.d/mandos-client $PARAMS`
systemctl --system set-environment KSPP=$KSPP
systemctl --system set-environment KSPPCNT=$KSPPCNT
echo -n $KSPP;
exit 0;
