#!/usr/bin/env bash

set -e

if ! [ -f /etc/crypttab ]; then
  echo "/etc/crypttab does not exist. Please make sure that you created /etc/crypttab."
  exit 1;
fi

for target in `grep '/sbin/mandos-keyscript' /etc/crypttab | awk '{print $1}'`; do
  /usr/sbin/cryptdisks_start $target
done


if [ "$POSTSTART_SERVICES" = '' ]; then
  echo "INFO: You can optionally define POSTSTART_SERVICES in /etc/sysconfig/mandos-keyscript.";
fi


if [ "$POSTSTART_KMODS" != '' ]; then
  for kmod in "$POSTSTART_KMODS"; do
    WAITTIME=30
    while [ "$WAITTIME" -gt 0 ]; do
      if [ "`lsmod | grep \"^$kmod\s\" | awk '{print $1}'`" = '' ]; then
        WAITTIME=$((WAITTIME-1));
        sleep 1;
      else
        echo "$kmod loaded"
        break;
      fi
    done
  done
fi


if [ "$POSTSTART_SERVICES" != '' ]; then
  for service in "$POSTSTART_SERVICES"; do
    /bin/systemctl start $service
  done
fi

if [ "$POSTSTART_CMD" != '' ]; then
  eval $POSTSTART_CMD
fi
